[package]
name = "gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess-engine = { path = "../chess-engine" }
relm = "0.22"
relm-derive = "0.22"
gtk = "0.14"